sudo: required
services:
  - docker
language: elixir
elixir:
  - 1.3.3
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      make
    fi
